# exclude SafeMath when calculating test coverage
# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths
reports:
  exclude_contracts:
    - SafeMath

networks:
  default: mainnet-fork

compiler:
  solc:
    version: 0.8.11
    optimizer:
      enabled: true
      runs: 800